stages:
  - deploy

deploy:
  stage: deploy
  variables:
    PACKAGE_NAME: S4APIWrapper  
    PACKAGE_PATH: BUILD/NuGet/${PACKAGE_NAME}.${CI_COMMIT_TAG}
    PACKAGE_REPO_ID: 21 # central project for packages https://gitlab.settlers4-hd.com/s4-plugins/modapi/packages
    API_URL: https://gitlab.settlers4-hd.com/api/v4/projects
  script:
    - msbuild -t:restore,clean,build -p:Configuration=Release
    - msbuild -t:pack -p:Configuration=Release
    - echo "${API_URL}/${PACKAGE_REPO_ID}/packages/nuget/index.json"
    - echo '<?xml version="1.0" encoding="utf-8"?><configuration></configuration>' | Out-File -Encoding UTF8 "./Upload.Nuget.Config"
    - nuget sources add -Source "${API_URL}/${PACKAGE_REPO_ID}/packages/nuget/index.json" -Name gitlab -Username gitlab-ci-token -Password $CI_JOB_TOKEN -StorePasswordInClearText -ConfigFile "./Upload.Nuget.Config"
    - nuget push "${PACKAGE_PATH}.nupkg" -Source gitlab -ConfigFile "./Upload.Nuget.Config"
    - nuget push "${PACKAGE_PATH}.snupkg" -Source gitlab -ConfigFile "./Upload.Nuget.Config"
  rules:
    - if: $CI_COMMIT_TAG